#!/bin/bash

echo "✅ 插件已正确安装到 DSH！"
echo ""
echo "📍 安装位置:"
echo "   符号链接: ~/.dsh/plugins/dsh-provider-detector"
echo "   实际位置: ~/github/dsh-provider-detector"
echo ""
echo "⚙️  配置文件:"
echo "   ~/.dsh/settings.yaml"
echo ""
echo "🔄 请重启 DSH 来加载插件:"
echo ""
echo "   方式 1: 重启桌面应用"
echo "     1. 关闭 DeepSeek Harness 应用"
echo "     2. 重新打开 DeepSeek Harness 应用"
echo ""
echo "   方式 2: 命令行重启"
echo "     pkill -f 'dsh.*web'"
echo "     dsh --profile web"
echo ""
echo "🔍 重启后验证:"
echo "   1. 打开 DSH Web 界面: http://localhost:3080"
echo "   2. 进入 Settings（设置）-> Plugins（插件）"
echo "   3. 应该能看到 'dsh-provider-detector' 插件"
echo ""
echo "📊 或者在浏览器控制台测试 API:"
echo "   fetch('/api/provider-detector/providers')"
echo "     .then(r => r.json())"
echo "     .then(console.log)"
echo ""
